describe('template spec', () => {
    it('passes', () => {


        //  ADMIN ACCOUNT
        
        // Users can create custom tags (41)
        cy.visit('https://alpha.xpropeller.com/signin')
      cy.wait(3000)
      cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
      cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
      cy.wait(3000)
      cy.get('.px-2').type('123456{enter}')
      cy.wait(3000)
       // documents
       cy.get('[href="/dms"]').click()
       cy.wait(3000)
       //select file
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
      cy.wait(3000)
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
      cy.wait(3000)
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
      cy.wait(3000)
      // create tag
      cy.contains('Add Tag').click()
      cy.wait(3000)
      cy.get('form > .w-full > .border').click()
      cy.wait(3000)
      cy.get('form > .w-full > .border').type('Puppy')
      cy.wait(3000)
      // add
      cy.get('.w-full > .bg-blue-600').click()
      cy.wait(3000)
      cy.get(':nth-child(3) > .border-b').click()
      // submit
      cy.get('.my-5 > :nth-child(1) > .px-4').click()
      cy.wait(3000)
      cy.reload()
      cy.wait(5000)
      //logout
      cy.get('[href="/logout"]').click()


      

        // Users can Delete custom tags (43)
        cy.visit('https://alpha.xpropeller.com/signin')
        cy.wait(3000)
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
        cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
        cy.wait(3000)
        cy.get('.px-2').type('123456{enter}')
        cy.wait(3000)
        // documents
        cy.get('[href="/dms"]').click()
        cy.wait(3000)
        //select file
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
        cy.wait(3000)
        // create tag
        cy.contains('Add Tag').click()
        cy.wait(3000)
        cy.get('.relative > :nth-child(1) > .border-b').trigger('mouseover')
        cy.get('.relative > :nth-child(1) > .border-b').should('be.visible')
        cy.wait(3000)
        cy.get('.relative > .flex > .p-1 > .flex > .p-1:nth-child(2)').click()
        cy.get('.absolute > .border-b').click()
        cy.wait(3000)
        cy.get('.bg-white > .ml-auto > .text-white').click()
        cy.wait(3000)
        cy.get(':nth-child(2) > .px-4').click()
        cy.wait(3000)
        //logout
        cy.get('[href="/logout"]').click()

        // Users can Edit custom tags (45)
        cy.visit('https://alpha.xpropeller.com/signin')
        cy.wait(3000)
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
        cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
        cy.wait(3000)
        cy.get('.px-2').type('123456{enter}')
        cy.wait(3000)
        // documents
        cy.get('[href="/dms"]').click()
        cy.wait(3000)
        //select file
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
        cy.wait(3000)
        // create tag
        cy.contains('Add Tag').click()
        cy.wait(3000)
        cy.get('.relative > :nth-child(1) > .border-b').trigger('mouseover')
        cy.get('.relative > :nth-child(1) > .border-b').should('be.visible')
        cy.wait(3000)
        cy.get('.relative > .flex > .p-1 > .flex > .p-1:nth-child(2)').click()
        cy.wait(3000)
        cy.get('.relative > :nth-child(1) > .absolute > :nth-child(2)').click()
        cy.wait(3000)
        cy.get(':nth-child(1) > .border-b > .flex > .p-1').clear().type('CR7{enter}')
        cy.wait(3000)
        cy.get(':nth-child(2) > .px-4').click()
        cy.wait(3000)
        //logout
        cy.get('[href="/logout"]').click()

        // Users can add custom tags to the document (47)
        cy.visit('https://alpha.xpropeller.com/signin')
        cy.wait(3000)
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
        cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
        cy.wait(3000)
        cy.get('.px-2').type('123456{enter}')
        cy.wait(3000)
         // documents
         cy.get('[href="/dms"]').click()
         cy.wait(3000)
         //select file
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
        cy.wait(3000)
        // add tag
        cy.contains('Add Tag').click()
        cy.wait(3000)
        cy.get('.relative > .flex-col > .border-b').trigger('mouseover')
        cy.get('.relative > .flex-col > .border-b').should('be.visible')
        cy.wait(3000)
        cy.get('.relative > .flex-col > .border-b').click()
        cy.get('.my-5 > :nth-child(1) > .px-4').click()
        cy.reload()
        cy.wait(5000)
        //logout
        cy.get('[href="/logout"]').click()

        // Users can remove the custom tags from the document (49)
        cy.visit('https://alpha.xpropeller.com/signin')
        cy.wait(3000)
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
        cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
        cy.wait(3000)
        cy.get('.px-2').type('123456{enter}')
        cy.wait(3000)
         // documents
         cy.get('[href="/dms"]').click()
         cy.wait(3000)
         //select file
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
        cy.wait(3000)
        // add tag
        cy.contains('Add Tag').click()
        cy.wait(3000)
        cy.get('.space-x-2 > :nth-child(1) > .relative').trigger('mouseover')
        cy.get('.space-x-2 > :nth-child(1) > .relative').should('be.visible')
        cy.wait(3000)
        cy.get('.relative > .absolute > :nth-child(2)').click()
        cy.reload()
        cy.wait(7000)
         //logout
         cy.get('[href="/logout"]').click()


         // Users can add custom tags to the folders (51)
         cy.visit('https://alpha.xpropeller.com/signin')
         cy.wait(3000)
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
        cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
        cy.wait(3000)
        cy.get('.px-2').type('123456{enter}')
        cy.wait(3000)
         // documents
         cy.get('[href="/dms"]').click()
         cy.wait(3000)
         //select file
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
        cy.wait(3000)
        // add tag
        cy.contains('Add Tag').click()
        cy.wait(3000)
        cy.get('.relative > .flex-col > .border-b').trigger('mouseover')
        cy.get('.relative > .flex-col > .border-b').should('be.visible')
        cy.wait(3000)
        cy.get('.relative > .flex-col > .border-b').click()
        cy.get('.my-5 > :nth-child(1) > .px-4').click()
        cy.reload()
        cy.wait(5000)
        //logout
        cy.get('[href="/logout"]').click()


        // Users can remove the custom tags from the folders (53)
        cy.visit('https://alpha.xpropeller.com/signin')
        cy.wait(3000)
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
        cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
        cy.wait(3000)
        cy.get('.px-2').type('123456{enter}')
        cy.wait(3000)
         // documents
         cy.get('[href="/dms"]').click()
         cy.wait(3000)
         //select file
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
        cy.wait(3000)
        // add tag
        cy.contains('Add Tag').click()
        cy.wait(3000)
        cy.get('.space-x-2 > :nth-child(1) > .relative').trigger('mouseover')
        cy.get('.space-x-2 > :nth-child(1) > .relative').should('be.visible')
        cy.wait(3000)
        cy.get('.relative > .absolute > :nth-child(2)').click()
        cy.reload()
        cy.wait(7000)
         //logout
         cy.get('[href="/logout"]').click()


        // Color-coded tags for expiring documents (59) 
        cy.visit('https://alpha.xpropeller.com/signin')
        cy.wait(3000)
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
        cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
        cy.wait(3000)
        cy.get('.px-2').type('123456{enter}')
        cy.wait(3000)
         // documents
         cy.get('[href="/dms"]').click()
         cy.wait(3000)
         //select file
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
        cy.wait(3000)
        // metadata
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
        cy.wait(3000)
        cy.contains('Edit Metadata').click()
        cy.wait(3000)
        // fill metadata
        cy.get(':nth-child(1) > .px-2 > .mt-1 > .css-10u1y7e-control > .css-hlgwow').click()
        cy.get('#react-select-12-option-0').click()
        cy.wait(3000)
        cy.get(':nth-child(2) > :nth-child(1) > .mt-1 > .css-10u1y7e-control > .css-hlgwow').click()
        cy.get('#react-select-13-option-5').click()
        cy.wait(3000)
        cy.get(':nth-child(2) > .mt-1 > .css-10u1y7e-control > .css-hlgwow').click()
        cy.get('#react-select-14-option-2').click()
        cy.wait(3000)
        cy.get(':nth-child(3) > .mt-1 > .css-10u1y7e-control > .css-hlgwow').click()
        cy.get('#react-select-15-option-0').click()
        cy.wait(3000)
        cy.get('.p-3 > :nth-child(1) > input').click()
        cy.wait(3000)
        cy.get('.inline-flex > :nth-child(1) > :nth-child(2) > .px-2').click()
        cy.wait(3000)
        cy.get('.p-4 > .flex > div:nth-child(1) > div > .px-2').click()
        cy.wait(3000)
        cy.get('.p-4 > .flex > div:nth-child(1) > div > .px-2').type('2024-01-28')
        cy.wait(3000)
        cy.get('.p-4 > .flex:nth-child(2) > div:nth-child(2) > div > .px-2').click()
        cy.wait(3000)
        cy.get('.p-4 > .flex:nth-child(2) > div:nth-child(2) > div > .px-2').type('2024-02-11')
        cy.wait(3000)
        cy.get('.bg-gray-100 > .bg-blue-500').click()
        cy.wait(3000)
        cy.reload()
        cy.wait(7000)
        //logout
        cy.get('[href="/logout"]').click()
        


        // USER ACCOUNT

         // Users can create custom tags (42)
         cy.visit('https://alpha.xpropeller.com/signin')
         cy.wait(3000)
      cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
      cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
      cy.wait(3000)
      cy.get('.px-2').type('123456{enter}')
      cy.wait(3000)
       // documents
       cy.get('[href="/dms"]').click()
       cy.wait(3000)
       //select file
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
      cy.wait(3000)
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
      cy.wait(3000)
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
      cy.wait(3000)
      // create tag
      cy.contains('Add Tag').click()
      cy.wait(3000)
      cy.get('form > .w-full > .border').click()
      cy.wait(3000)
      cy.get('form > .w-full > .border').type('Puppy')
      cy.wait(3000)
      // add
      cy.get('.w-full > .bg-blue-600').click()
      cy.wait(3000)
      cy.get(':nth-child(3) > .border-b').click()
      // submit
      cy.get('.my-5 > :nth-child(1) > .px-4').click()
      cy.wait(3000)
      cy.reload()
      cy.wait(5000)
      //logout
      cy.get('[href="/logout"]').click()


      

          // Users can Delete custom tags (44)
          cy.visit('https://alpha.xpropeller.com/signin')
          cy.wait(3000)
          cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
          cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
          cy.wait(3000)
          cy.get('.px-2').type('123456{enter}')
          cy.wait(3000)
          // documents
          cy.get('[href="/dms"]').click()
          cy.wait(3000)
          //select file
          cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
          cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
          cy.wait(3000)
          cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
          cy.wait(3000)
          cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
          cy.wait(3000)
          // create tag
          cy.contains('Add Tag').click()
          cy.wait(3000)
          cy.get('.relative > :nth-child(1) > .border-b').trigger('mouseover')
          cy.get('.relative > :nth-child(1) > .border-b').should('be.visible')
          cy.wait(3000)
          cy.get('.relative > .flex > .p-1 > .flex > .p-1:nth-child(2)').click()
          cy.get('.absolute > .border-b').click()
          cy.wait(3000)
          cy.get('.bg-white > .ml-auto > .text-white').click()
          cy.wait(3000)
          cy.get(':nth-child(2) > .px-4').click()
          cy.wait(3000)
          //logout
          cy.get('[href="/logout"]').click()


          // Users can Edit custom tags (46)
          cy.visit('https://alpha.xpropeller.com/signin')
          cy.wait(3000)
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
        cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
        cy.wait(3000)
        cy.get('.px-2').type('123456{enter}')
        cy.wait(3000)
        // documents
        cy.get('[href="/dms"]').click()
        cy.wait(3000)
        //select file
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
        cy.wait(3000)
        // create tag
        cy.contains('Add Tag').click()
        cy.wait(3000)
        cy.get('.relative > :nth-child(1) > .border-b').trigger('mouseover')
        cy.get('.relative > :nth-child(1) > .border-b').should('be.visible')
        cy.wait(3000)
        cy.get('.relative > .flex > .p-1 > .flex > .p-1:nth-child(2)').click()
        cy.wait(3000)
        cy.get('.relative > :nth-child(1) > .absolute > :nth-child(2)').click()
        cy.wait(3000)
        cy.get(':nth-child(1) > .border-b > .flex > .p-1').clear().type('CR7{enter}')
        cy.wait(3000)
        cy.get(':nth-child(2) > .px-4').click()
        cy.wait(3000)
        //logout
        cy.get('[href="/logout"]').click()

          // Users can add custom tags to the document (48)
          cy.visit('https://alpha.xpropeller.com/signin')
          cy.wait(3000)
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
        cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
        cy.wait(3000)
        cy.get('.px-2').type('123456{enter}')
        cy.wait(3000)
         // documents
         cy.get('[href="/dms"]').click()
         cy.wait(3000)
         //select file
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
        cy.wait(3000)
        // add tag
        cy.contains('Add Tag').click()
        cy.wait(3000)
        cy.get('.relative > .flex-col > .border-b').trigger('mouseover')
        cy.get('.relative > .flex-col > .border-b').should('be.visible')
        cy.wait(3000)
        cy.get('.relative > .flex-col > .border-b').click()
        cy.get('.my-5 > :nth-child(1) > .px-4').click()
        cy.reload()
        cy.wait(5000)
        //logout
        cy.get('[href="/logout"]').click()


        // Users can remove the custom tags from the document (50)
        cy.visit('https://alpha.xpropeller.com/signin')
        cy.wait(3000)
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
        cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
        cy.wait(3000)
        cy.get('.px-2').type('123456{enter}')
        cy.wait(3000)
         // documents
         cy.get('[href="/dms"]').click()
         cy.wait(3000)
         //select file
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
        cy.wait(3000)
        // add tag
        cy.contains('Add Tag').click()
        cy.wait(3000)
        cy.get('.space-x-2 > :nth-child(1) > .relative').trigger('mouseover')
        cy.get('.space-x-2 > :nth-child(1) > .relative').should('be.visible')
        cy.wait(3000)
        cy.get('.relative > .absolute > :nth-child(2)').click()
        cy.reload()
        cy.wait(7000)
         //logout
         cy.get('[href="/logout"]').click()


         // Users can add custom tags to the folders (52)
         cy.visit('https://alpha.xpropeller.com/signin')
         cy.wait(3000)
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
        cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
        cy.wait(3000)
        cy.get('.px-2').type('123456{enter}')
        cy.wait(3000)
         // documents
         cy.get('[href="/dms"]').click()
         cy.wait(3000)
         //select file
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
        cy.wait(3000)
        // add tag
        cy.contains('Add Tag').click()
        cy.wait(3000)
        cy.get('.relative > .flex-col > .border-b').trigger('mouseover')
        cy.get('.relative > .flex-col > .border-b').should('be.visible')
        cy.wait(3000)
        cy.get('.relative > .flex-col > .border-b').click()
        cy.get('.my-5 > :nth-child(1) > .px-4').click()
        cy.reload()
        cy.wait(5000)
        //logout
        cy.get('[href="/logout"]').click()


        // Users can remove the custom tags from the folders (54)
        cy.visit('https://alpha.xpropeller.com/signin')
        cy.wait(3000)
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
        cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
        cy.wait(3000)
        cy.get('.px-2').type('123456{enter}')
        cy.wait(3000)
         // documents
         cy.get('[href="/dms"]').click()
         cy.wait(3000)
         //select file
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
         cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
        cy.wait(3000)
        // add tag
        cy.contains('Add Tag').click()
        cy.wait(3000)
        cy.get('.space-x-2 > :nth-child(1) > .relative').trigger('mouseover')
        cy.get('.space-x-2 > :nth-child(1) > .relative').should('be.visible')
        cy.wait(3000)
        cy.get('.relative > .absolute > :nth-child(2)').click()
        cy.reload()
        cy.wait(7000)
         //logout
         cy.get('[href="/logout"]').click()

        // Color-coded tags for expiring documents (60) 
        cy.visit('https://alpha.xpropeller.com/signin')
        cy.wait(3000)
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
        cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
        cy.wait(3000)
        cy.get('.px-2').type('123456{enter}')
        cy.wait(3000)
        // documents
        cy.get('[href="/dms"]').click()
        cy.wait(3000)
        //select file
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
        cy.wait(3000)
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
        cy.wait(3000)
        // metadata
        cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
        cy.wait(3000)
        cy.contains('Edit Metadata').click()
        cy.wait(3000)
        // fill metadata
        cy.get(':nth-child(1) > .px-2 > .mt-1 > .css-10u1y7e-control > .css-hlgwow').click()
        cy.get('#react-select-12-option-0').click()
        cy.wait(3000)
        cy.get(':nth-child(2) > :nth-child(1) > .mt-1 > .css-10u1y7e-control > .css-hlgwow').click()
        cy.get('#react-select-13-option-2').click()
        cy.wait(3000)
        cy.get(':nth-child(2) > .mt-1 > .css-10u1y7e-control > .css-hlgwow').click()
        cy.get('#react-select-14-option-2').click()
        cy.wait(3000)
        cy.get(':nth-child(3) > .mt-1 > .css-10u1y7e-control > .css-hlgwow').click()
        cy.get('#react-select-15-option-0').click()
        cy.wait(3000)
        cy.get('.p-3 > :nth-child(1) > input').click()
        cy.wait(3000)
        cy.get('.inline-flex > :nth-child(1) > :nth-child(2) > .px-2').click()
        cy.wait(3000)
        cy.get('.p-4 > .flex > div:nth-child(1) > div > .px-2').click()
        cy.wait(3000)
        cy.get('.p-4 > .flex > div:nth-child(1) > div > .px-2').type('2024-01-28')
        cy.wait(3000)
        cy.get('.p-4 > .flex:nth-child(2) > div:nth-child(2) > div > .px-2').click()
        cy.wait(3000)
        cy.get('.p-4 > .flex:nth-child(2) > div:nth-child(2) > div > .px-2').type('2024-02-11')
        cy.wait(3000)
        cy.get('.bg-gray-100 > .bg-blue-500').click()
        cy.wait(3000)
        cy.reload()
        cy.wait(7000)
        //logout
        cy.get('[href="/logout"]').click()
        
    })
})