describe('template spec', () => {
    it('passes', () => {
       

     // ADMIN Account

     //set up reminder for Documents (306)
     cy.visit('https://alpha.xpropeller.com/signin')
     cy.wait(3000)
     cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
     cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
     cy.wait(3000)
     cy.get('.px-2').type('123456{enter}')
     cy.wait(3000)
      // documents
      cy.get('[href="/dms"]').click()
      cy.wait(3000)
      //select file
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
      cy.wait(3000)
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
      cy.wait(3000)
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
      // reminder
      cy.contains('Set Reminder').click()
      cy.wait(3000)
      cy.get(':nth-child(2) > .p-1 > input').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').type('2024-02-27')
      cy.wait(3000)
      cy.get('.pt-3 > :nth-child(3) > :nth-child(2) > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(2) > div > .px-2').type('2024-03-29')
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').type('18:17')
      cy.wait(3000)
      cy.get('.z-10 > .bg-white > .p-4 > .pt-3 > .flex:nth-child(5)').click()
      cy.wait(3000)
      cy.get('#react-select-13-option-1').click()
      cy.wait(3000)
      cy.get('.ml-12 > .css-10u1y7e-control').click()
      cy.wait(3000)
      cy.get('#react-select-12-option-0').click()
      cy.wait(3000)
      cy.get('.p-2 > .bg-blue-500').click()
      cy.wait(3000)
      cy.get('.justify-end > .ml-auto').click()
      cy.wait(3000)
      //logout
      cy.get('[href="/logout"]').click()



      //Reminder Space (310)
      cy.visit('https://alpha.xpropeller.com/signin')
      cy.wait(3000)
     cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
     cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
     cy.wait(3000)
     cy.get('.px-2').type('123456{enter}')
     cy.wait(3000)
      // documents
      cy.get('[href="/dms"]').click()
      cy.wait(3000)
      //select file
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
      cy.wait(3000)
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
      cy.wait(3000)
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
      // reminder
      cy.contains('Set Reminder').click()
      cy.wait(3000)
      cy.get(':nth-child(2) > .p-1 > input').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').type('2024-02-27')
      cy.wait(3000)
      cy.get('.pt-3 > :nth-child(3) > :nth-child(2) > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(2) > div > .px-2').type('2024-03-29')
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').type('18:17')
      cy.wait(3000)
      cy.get('.z-10 > .bg-white > .p-4 > .pt-3 > .flex:nth-child(5)').click()
      cy.wait(3000)
      cy.get('#react-select-13-option-1').click()
      cy.wait(3000)
      cy.get('.ml-12 > .css-10u1y7e-control').click()
      cy.wait(3000)
      cy.get('#react-select-12-option-0').click()
      cy.wait(3000)
      cy.get('.p-2 > .bg-blue-500').click()
      cy.wait(3000)
      cy.get('.justify-end > .ml-auto').click()
      cy.wait(3000)
      cy.get('[href="/reminders"]').click()
      cy.wait(5000)
      //logout
      cy.get('[href="/logout"]').click()


      //Frequency (316)
      cy.visit('https://alpha.xpropeller.com/signin')
      cy.wait(3000)
     cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
     cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
     cy.wait(3000)
     cy.get('.px-2').type('123456{enter}')
     cy.wait(3000)
      // documents
      cy.get('[href="/dms"]').click()
      cy.wait(3000)
      //select file
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
      cy.wait(3000)
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
      cy.wait(3000)
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
      // reminder
      cy.contains('Set Reminder').click()
      cy.wait(3000)
      cy.get(':nth-child(2) > .p-1 > input').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').type('2024-02-27')
      cy.wait(3000)
      cy.get('.pt-3 > :nth-child(3) > :nth-child(2) > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(2) > div > .px-2').type('2024-03-29')
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').type('18:17')
      cy.wait(3000)
      cy.get('.z-10 > .bg-white > .p-4 > .pt-3 > .flex:nth-child(5)').click()
      cy.wait(3000)
      cy.get('#react-select-13-option-1').click()
      cy.wait(3000)
      cy.get('.ml-12 > .css-10u1y7e-control').click()
      cy.wait(3000)
      cy.get('#react-select-12-option-0').click()
      cy.wait(3000)
      cy.get('.p-2 > .bg-blue-500').click()
      cy.wait(3000)
      cy.get('.justify-end > .ml-auto').click()
      cy.wait(5000)
      //notification    
      cy.get('.w-16 > .cursor-pointer').click()
      cy.wait(3000)
      // logout
      cy.get('[href="/logout"]').click()


      //Delegation (318)
      cy.visit('https://alpha.xpropeller.com/signin')
      cy.wait(3000)
      cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
      cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
      cy.wait(3000)
      cy.get('.px-2').type('123456{enter}')
      cy.wait(3000)
      cy.get('[href="/reminders"]').click()
      cy.wait(3000)
      cy.get('.space-x-3 > .flex-col > :nth-child(1) > .p-1 > .flex > .p-2').click()
      cy.wait(3000)
      cy.get('.ml-auto > .text-white').click()
      cy.reload()
      cy.wait(5000)
      //logout
      cy.get('[href="/logout"]').click()
      cy.wait(3000)


      // set up Multi- reminder for Documents(320)
      cy.visit('https://alpha.xpropeller.com/signin')
      cy.wait(3000)
      cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
      cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
      cy.wait(3000)
      cy.get('.px-2').type('123456{enter}')
      cy.wait(3000)
       // documents
       cy.get('[href="/dms"]').click()
       cy.wait(3000)
       //select file
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
       cy.wait(3000)
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
       cy.wait(3000)
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
       // reminder
       cy.contains('Set Reminder').click()
       cy.wait(3000)
       cy.get(':nth-child(2) > .p-1 > input').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').type('2024-02-27')
       cy.wait(3000)
       cy.get('.pt-3 > :nth-child(3) > :nth-child(2) > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(2) > div > .px-2').type('2024-03-29')
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').type('18:17')
       cy.wait(3000)
       cy.get('.z-10 > .bg-white > .p-4 > .pt-3 > .flex:nth-child(5)').click()
       cy.wait(3000)
       cy.get('#react-select-13-option-1').click()
       cy.wait(3000)
       cy.get('.ml-12 > .css-10u1y7e-control').click()
       cy.wait(3000)
       cy.get('#react-select-12-option-0').click()
       cy.wait(3000)
       cy.get('.p-2 > .bg-blue-500').click()
       cy.wait(3000)
       cy.get('.justify-end > .ml-auto').click()
       cy.wait(3000)
       cy.reload()
       cy.wait(5000)
       //select file
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
       cy.wait(3000)
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
       cy.wait(3000)
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
       // reminder
       cy.contains('Set Reminder').click()
       cy.wait(3000)
       cy.get(':nth-child(2) > .p-1 > input').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').type('2024-02-27')
       cy.wait(3000)
       cy.get('.pt-3 > :nth-child(3) > :nth-child(2) > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(2) > div > .px-2').type('2024-03-29')
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').type('18:17')
       cy.wait(3000)
       cy.get('.z-10 > .bg-white > .p-4 > .pt-3 > .flex:nth-child(5)').click()
       cy.wait(3000)
       cy.get('#react-select-13-option-1').click()
       cy.wait(3000)
       cy.get('.ml-12 > .css-10u1y7e-control').click()
       cy.wait(3000)
       cy.get('#react-select-12-option-0').click()
       cy.wait(3000)
       cy.get('.p-2 > .bg-blue-500').click()
       cy.wait(3000)
       cy.get('.justify-end > .ml-auto').click()
       cy.wait(3000)
       cy.reload()
       cy.wait(5000)
       //select file
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
       cy.wait(3000)
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
       cy.wait(3000)
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
       // reminder
       cy.contains('Set Reminder').click()
       cy.wait(3000)
       cy.get(':nth-child(2) > .p-1 > input').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').type('2024-02-27')
       cy.wait(3000)
       cy.get('.pt-3 > :nth-child(3) > :nth-child(2) > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(2) > div > .px-2').type('2024-03-29')
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').type('18:17')
       cy.wait(3000)
       cy.get('.z-10 > .bg-white > .p-4 > .pt-3 > .flex:nth-child(5)').click()
       cy.wait(3000)
       cy.get('#react-select-13-option-1').click()
       cy.wait(3000)
       cy.get('.ml-12 > .css-10u1y7e-control').click()
       cy.wait(3000)
       cy.get('#react-select-12-option-0').click()
       cy.wait(3000)
       cy.get('.p-2 > .bg-blue-500').click()
       cy.wait(3000)
       cy.get('.justify-end > .ml-auto').click()
       cy.wait(3000)
       cy.reload()
       cy.wait(5000)
       //logout
       cy.get('[href="/logout"]').click()


       

        
        // USER ACCOUNT

        //set up reminder for Documents (301)
        cy.visit('https://alpha.xpropeller.com/signin')
      cy.wait(3000)
      cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
      cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
      cy.wait(3000)
      cy.get('.px-2').type('123456{enter}')
      cy.wait(3000)
      // documents
      cy.get('[href="/dms"]').click()
      cy.wait(3000)
      //select file
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
      cy.wait(3000)
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
      cy.wait(3000)
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
      // reminder
      cy.contains('Set Reminder').click()
      cy.wait(3000)
      cy.get(':nth-child(2) > .p-1 > input').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').type('2024-02-27')
      cy.wait(3000)
      cy.get('.pt-3 > :nth-child(3) > :nth-child(2) > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(2) > div > .px-2').type('2024-03-29')
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').type('18:17')
      cy.wait(3000)
      cy.get('.z-10 > .bg-white > .p-4 > .pt-3 > .flex:nth-child(5)').click()
      cy.wait(3000)
      cy.get('#react-select-13-option-1').click()
      cy.wait(3000)
      cy.get('.ml-12 > .css-10u1y7e-control').click()
      cy.wait(3000)
      cy.get('#react-select-12-option-0').click()
      cy.wait(3000)
      cy.get('.p-2 > .bg-blue-500').click()
      cy.wait(3000)
      cy.get('.justify-end > .ml-auto').click()
      cy.wait(3000)
      //logout
      cy.get('[href="/logout"]').click()


      //Reminder Space (311)
      cy.visit('https://alpha.xpropeller.com/signin')
      cy.wait(3000)
     cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
     cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
     cy.wait(3000)
     cy.get('.px-2').type('123456{enter}')
     cy.wait(3000)
      // documents
      cy.get('[href="/dms"]').click()
      cy.wait(3000)
      //select file
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
      cy.wait(3000)
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
      cy.wait(3000)
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
      // reminder
      cy.contains('Set Reminder').click()
      cy.wait(3000)
      cy.get(':nth-child(2) > .p-1 > input').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').type('2024-02-27')
      cy.wait(3000)
      cy.get('.pt-3 > :nth-child(3) > :nth-child(2) > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(2) > div > .px-2').type('2024-03-29')
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').type('18:17')
      cy.wait(3000)
      cy.get('.z-10 > .bg-white > .p-4 > .pt-3 > .flex:nth-child(5)').click()
      cy.wait(3000)
      cy.get('#react-select-13-option-1').click()
      cy.wait(3000)
      cy.get('.ml-12 > .css-10u1y7e-control').click()
      cy.wait(3000)
      cy.get('#react-select-12-option-0').click()
      cy.wait(3000)
      cy.get('.p-2 > .bg-blue-500').click()
      cy.wait(3000)
      cy.get('.justify-end > .ml-auto').click()
      cy.wait(3000)
      cy.get('[href="/reminders"]').click()
      cy.wait(5000)
      //logout
      cy.get('[href="/logout"]').click()


  
      //Frequency (317)
      cy.visit('https://alpha.xpropeller.com/signin')
      cy.wait(3000)
     cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
     cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
     cy.wait(3000)
     cy.get('.px-2').type('123456{enter}')
     cy.wait(3000)
      // documents
      cy.get('[href="/dms"]').click()
      cy.wait(3000)
      //select file
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
      cy.wait(3000)
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
      cy.wait(3000)
      cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
      // reminder
      cy.contains('Set Reminder').click()
      cy.wait(3000)
      cy.get(':nth-child(2) > .p-1 > input').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').type('2024-02-27')
      cy.wait(3000)
      cy.get('.pt-3 > :nth-child(3) > :nth-child(2) > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(2) > div > .px-2').type('2024-03-29')
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').click()
      cy.wait(3000)
      cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').type('18:17')
      cy.wait(3000)
      cy.get('.z-10 > .bg-white > .p-4 > .pt-3 > .flex:nth-child(5)').click()
      cy.wait(3000)
      cy.get('#react-select-13-option-1').click()
      cy.wait(3000)
      cy.get('.ml-12 > .css-10u1y7e-control').click()
      cy.wait(3000)
      cy.get('#react-select-12-option-0').click()
      cy.wait(3000)
      cy.get('.p-2 > .bg-blue-500').click()
      cy.wait(3000)
      cy.get('.justify-end > .ml-auto').click()
      cy.wait(5000)
      //notification    
      cy.get('.w-16 > .cursor-pointer').click()
      cy.wait(3000)
      // logout
      cy.get('[href="/logout"]').click()


      //Delegation (319)
      cy.visit('https://alpha.xpropeller.com/signin')
      cy.wait(3000)
      cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
      cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
      cy.wait(3000)
      cy.get('.px-2').type('123456{enter}')
      cy.wait(3000)
      cy.get('[href="/reminders"]').click()
      cy.wait(3000)
      cy.get('.space-x-3 > .flex-col > :nth-child(1) > .p-1 > .flex > .p-2').click()
      cy.wait(3000)
      cy.get('.ml-auto > .text-white').click()
      cy.reload()
      cy.wait(5000)
      //logout
      cy.get('[href="/logout"]').click()
      cy.wait(3000)


      // set up Multi- reminder for Documents(321)
      cy.visit('https://alpha.xpropeller.com/signin')
      cy.wait(3000)
      cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
      cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
      cy.wait(3000)
      cy.get('.px-2').type('123456{enter}')
      cy.wait(3000)
       // documents
       cy.get('[href="/dms"]').click()
       cy.wait(3000)
       //select file
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
       cy.wait(3000)
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
       cy.wait(3000)
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
       // reminder
       cy.contains('Set Reminder').click()
       cy.wait(3000)
       cy.get(':nth-child(2) > .p-1 > input').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').type('2024-02-27')
       cy.wait(3000)
       cy.get('.pt-3 > :nth-child(3) > :nth-child(2) > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(2) > div > .px-2').type('2024-03-29')
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').type('18:17')
       cy.wait(3000)
       cy.get('.z-10 > .bg-white > .p-4 > .pt-3 > .flex:nth-child(5)').click()
       cy.wait(3000)
       cy.get('#react-select-13-option-1').click()
       cy.wait(3000)
       cy.get('.ml-12 > .css-10u1y7e-control').click()
       cy.wait(3000)
       cy.get('#react-select-12-option-0').click()
       cy.wait(3000)
       cy.get('.p-2 > .bg-blue-500').click()
       cy.wait(3000)
       cy.get('.justify-end > .ml-auto').click()
       cy.wait(3000)
       cy.reload()
       cy.wait(5000)
       //select file
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
       cy.wait(3000)
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
       cy.wait(3000)
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
       // reminder
       cy.contains('Set Reminder').click()
       cy.wait(3000)
       cy.get(':nth-child(2) > .p-1 > input').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').type('2024-02-27')
       cy.wait(3000)
       cy.get('.pt-3 > :nth-child(3) > :nth-child(2) > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(2) > div > .px-2').type('2024-03-29')
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').type('18:17')
       cy.wait(3000)
       cy.get('.z-10 > .bg-white > .p-4 > .pt-3 > .flex:nth-child(5)').click()
       cy.wait(3000)
       cy.get('#react-select-13-option-1').click()
       cy.wait(3000)
       cy.get('.ml-12 > .css-10u1y7e-control').click()
       cy.wait(3000)
       cy.get('#react-select-12-option-0').click()
       cy.wait(3000)
       cy.get('.p-2 > .bg-blue-500').click()
       cy.wait(3000)
       cy.get('.justify-end > .ml-auto').click()
       cy.wait(3000)
       cy.reload()
       cy.wait(5000)
       //select file
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').trigger('mouseover')
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').should('be.visible')
       cy.wait(3000)
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').click()
       cy.wait(3000)
       cy.get('[style="position: absolute; left: 0px; top: 40px; height: 67px; width: 100%;"]').rightclick()
       // reminder
       cy.contains('Set Reminder').click()
       cy.wait(3000)
       cy.get(':nth-child(2) > .p-1 > input').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').type('2024-02-27')
       cy.wait(3000)
       cy.get('.pt-3 > :nth-child(3) > :nth-child(2) > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(2) > div > .px-2').type('2024-03-29')
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').click()
       cy.wait(3000)
       cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').type('18:17')
       cy.wait(3000)
       cy.get('.z-10 > .bg-white > .p-4 > .pt-3 > .flex:nth-child(5)').click()
       cy.wait(3000)
       cy.get('#react-select-13-option-1').click()
       cy.wait(3000)
       cy.get('.ml-12 > .css-10u1y7e-control').click()
       cy.wait(3000)
       cy.get('#react-select-12-option-0').click()
       cy.wait(3000)
       cy.get('.p-2 > .bg-blue-500').click()
       cy.wait(3000)
       cy.get('.justify-end > .ml-auto').click()
       cy.wait(3000)
       cy.reload()
       cy.wait(5000)
       //logout
       cy.get('[href="/logout"]').click()


      


      



     
   


        })
})