describe('template spec', () => {
    it('passes', () => {
        
    // ADMIN ACCOUNT

    //Users Can Select Data To Create  Dashboards(336)
    cy.visit('https://alpha.xpropeller.com/signin')
    cy.wait(3000)
     cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
     cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
     cy.wait(3000)
     cy.get('.px-2').type('123456{enter}')
     cy.wait(3000)
     // documents
     cy.get('[href="/dms"]').click()
     cy.wait(3000)
    //  dashboard
    cy.get('.space-y-1 > :nth-child(1) > .block').click()
    cy.wait(3000)
    cy.get('.right-10').click()
    cy.wait(3000)
    cy.get('.shadow > :nth-child(1)').click()
    cy.wait(3000)
    //logout
    cy.get('[href="/logout"]').click()


    // Schedule Reports To Be Sent To Users' Emails (345)
    cy.visit('https://alpha.xpropeller.com/signin')
    cy.wait(3000)
    //correct Credentials 
    cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
    cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
    cy.wait(3000)
    //correct 2fa
    cy.get('.px-2').type('123456{enter}')
    cy.wait(3000)
    //settings
    cy.get('[href="/settings"]').click()
    cy.wait(3000)
    // schedule report
    cy.get(':nth-child(11) > .flex').click()
    cy.wait(3000)
    cy.get('.ml-auto > .px-4').click()
    cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').click()
    cy.wait(3000)
    cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').type('2023-12-27')
    cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').click()
    cy.wait(3000)
    cy.get('.p-4 > .pt-3 > .flex:nth-child(2) > div > .px-2').type('2023-12-27')
    cy.get('.p-4 > .pt-3 > .flex:nth-child(2) > div > .px-2').click()
    cy.wait(3000)
    cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').type('18:17')
    cy.wait(3000)
    cy.get('.ml-12 > .css-10u1y7e-control').click()
    cy.wait(3000)
    cy.get('div > .ml-12 > #react-select-3-listbox > .css-qr46ko > #react-select-3-option-1').click()
    cy.wait(3000)
    cy.get('.w-\[230px\] > .css-azw1wt-control > .css-1wy0on6 > .css-15lsz6c-indicatorContainer > .css-8mmkcg').click()
    cy.wait(3000)
    cy.get('div > .w-\[230px\] > #react-select-4-listbox > .css-qr46ko > #react-select-4-option-0').click()
    cy.get('.z-10 > .bg-white > .p-4 > .pt-3 > .flex:nth-child(5)').click()
    cy.wait(3000)
    cy.get('#react-select-13-option-1').click()


    //Report Format - Excel(347)
    cy.visit('https://alpha.xpropeller.com/signin')
    cy.wait(3000)
    cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
    cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
    cy.wait(3000)
    cy.get('.px-2').type('123456{enter}')
    cy.wait(3000)
     //settings
     cy.get('[href="/settings"]').click()
     cy.wait(3000)
     cy.get('ul > :nth-child(3) > .flex').click()
     cy.wait(3000)
     cy.get('.bg-slate-200 > :nth-child(6)').click()
     cy.wait(3000)
     cy.get('.p-2 > .css-10u1y7e-control').click()
     cy.wait(3000)
     cy.get('#react-select-5-option-2').click()
     cy.wait(5000)
     cy.get('.items-center > .w-32').click()
     cy.wait(3000)
     cy.get('span > .text-gray-600').click()
     cy.wait(3000)
     //logout
     cy.get('[href="/logout"]').click()

     //Report Format - Pdf (349)
     cy.visit('https://alpha.xpropeller.com/signin')
     cy.wait(3000)
     cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
     cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
     cy.wait(3000)
     cy.get('.px-2').type('123456{enter}')
     cy.wait(3000)
     //settings
     cy.get('[href="/settings"]').click()
     cy.wait(3000)
     cy.get('ul > :nth-child(4) > .flex').click()
     cy.wait(3000)
     cy.get('.bg-slate-200 > :nth-child(6)').click()
     cy.wait(3000)
     cy.get('.p-2 > .css-10u1y7e-control').click()
     cy.wait(3000)
     cy.get('#react-select-5-option-2').click()
     cy.wait(5000)
     cy.get('.items-center > .w-32').click()
     cy.wait(3000)
     cy.get('.top-2 > :nth-child(2)').click()
     cy.wait(3000)
     //logout
     cy.get('[href="/logout"]').click()

     //Report Preferences: (253)
     cy.visit('https://alpha.xpropeller.com/signin')
     cy.wait(3000)
     cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
     cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
     cy.wait(3000)
     cy.get('.px-2').type('123456{enter}')
     cy.wait(3000)
      //settings
      cy.get('[href="/settings"]').click()
      cy.wait(3000)
      cy.get('ul > :nth-child(3) > .flex').click()
      cy.wait(3000)
      cy.get('.bg-slate-200 > :nth-child(6)').click()
      cy.wait(3000)
      cy.get('.p-2 > .css-10u1y7e-control').click()
      cy.wait(3000)
      cy.get('#react-select-5-option-2').click()
      cy.wait(5000)
      cy.get('.items-center > .w-32').click()
      cy.wait(3000)
      cy.get('.top-2 > :nth-child(2)').click()
      cy.wait(3000)
      //logout
      cy.get('[href="/logout"]').click()

      // User Activity Filtered By Facility: (355)
      cy.visit('https://alpha.xpropeller.com/signin')
      cy.wait(3000)
     cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
     cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
     cy.wait(3000)
     cy.get('.px-2').type('123456{enter}')
     cy.wait(3000)
     //settings
     cy.get('[href="/settings"]').click()
     cy.wait(5000)
     cy.get('ul > :nth-child(3) > .flex').click()
     cy.wait(3000)
     cy.get('.flex-row').click()
     cy.wait(3000)
     cy.get('#react-select-4-option-0').click()
     cy.wait(5000)
     cy.get('.flex-row > .items-center').click()
     cy.wait(3000)
     cy.get('.top-2 > :nth-child(2)').click()
     cy.wait(3000)
     //logout
     cy.get('[href="/logout"]').click()


          // User Activity Filtered By User (357)
          cy.visit('https://alpha.xpropeller.com/signin')
          cy.wait(3000)
          cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
          cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
          cy.wait(3000)
          cy.get('.px-2').type('123456{enter}')
          cy.wait(3000)
          //settings
          cy.get('[href="/settings"]').click()
          cy.wait(3000)
          cy.get('ul > :nth-child(3) > .flex').click()
          cy.wait(3000)
          cy.get('.bg-slate-200 > :nth-child(5)').click()
          cy.wait(3000)
          cy.get('.p-2 > .css-10u1y7e-control').click()
          cy.wait(3000)
          cy.get('#react-select-5-option-2').click()
          cy.wait(5000)
          cy.get('.flex-row > .items-center').click()
          cy.wait(3000)
          cy.get('.top-2 > :nth-child(1)').click()
          cy.wait(3000)
          //logout
          cy.get('[href="/logout"]').click()


    // USER ACCOUNT

     //Users Can Select Data To Create  Dashboards(337)
     cy.visit('https://alpha.xpropeller.com/signin')
     cy.wait(3000)
     cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
     cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
     cy.wait(3000)
     cy.get('.px-2').type('123456{enter}')
     cy.wait(3000)
     // documents
     cy.get('[href="/dms"]').click()
     cy.wait(3000)
    //  dashboard
    cy.get('.space-y-1 > :nth-child(1) > .block').click()
    cy.wait(3000)
    cy.get('.right-10').click()
    cy.wait(3000)
    cy.get('.shadow > :nth-child(1)').click()
    cy.wait(3000)
    //logout
    cy.get('[href="/logout"]').click()

    // Schedule Reports To Be Sent To Users' Emails (346)
    cy.visit('https://alpha.xpropeller.com/signin')
    cy.wait(3000)
    //correct Credentials 
    cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('xpropellerwws@gmail.com')
    cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
    cy.wait(3000)
    //correct 2fa
    cy.get('.px-2').type('123456{enter}')
    cy.wait(3000)
    //settings
    cy.get('[href="/settings"]').click()
    cy.wait(3000)
    // schedule report
    cy.get(':nth-child(11) > .flex').click()
    cy.wait(3000)
    cy.get('.ml-auto > .px-4').click()
    cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').click()
    cy.wait(3000)
    cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').type('2023-12-27')
    cy.get('.p-4 > .pt-3 > .flex:nth-child(1) > div > .px-2').click()
    cy.wait(3000)
    cy.get('.p-4 > .pt-3 > .flex:nth-child(2) > div > .px-2').type('2023-12-27')
    cy.get('.p-4 > .pt-3 > .flex:nth-child(2) > div > .px-2').click()
    cy.wait(3000)
    cy.get('.p-4 > .pt-3 > .flex:nth-child(3) > div > .px-2').type('18:17')
    cy.wait(3000)
    cy.get('.ml-12 > .css-10u1y7e-control').click()
    cy.wait(3000)
    cy.get('div > .ml-12 > #react-select-3-listbox > .css-qr46ko > #react-select-3-option-1').click()
    cy.wait(3000)
    cy.get('.w-\[230px\] > .css-azw1wt-control > .css-1wy0on6 > .css-15lsz6c-indicatorContainer > .css-8mmkcg').click()
    cy.wait(3000)
    cy.get('div > .w-\[230px\] > #react-select-4-listbox > .css-qr46ko > #react-select-4-option-0').click()
    cy.get('.z-10 > .bg-white > .p-4 > .pt-3 > .flex:nth-child(5)').click()
    cy.wait(3000)
    cy.get('#react-select-13-option-1').click()

    
     //Report Format - Excel(348)
     cy.visit('https://alpha.xpropeller.com/signin')
     cy.wait(3000)
     cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
     cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
     cy.wait(3000)
     cy.get('.px-2').type('123456{enter}')
     cy.wait(3000)
      //settings
      cy.get('[href="/settings"]').click()
      cy.wait(3000)
      cy.get('ul > :nth-child(3) > .flex').click()
      cy.wait(3000)
      cy.get('.bg-slate-200 > :nth-child(6)').click()
      cy.wait(3000)
      cy.get('.p-2 > .css-10u1y7e-control').click()
      cy.wait(3000)
      cy.get('#react-select-5-option-2').click()
      cy.wait(5000)
      cy.get('.items-center > .w-32').click()
      cy.wait(3000)
      cy.get('span > .text-gray-600').click()
      cy.wait(3000)
      //logout
      cy.get('[href="/logout"]').click()

        //Report Format - Pdf (350)
        cy.visit('https://alpha.xpropeller.com/signin')
        cy.wait(3000)
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
        cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
        cy.wait(3000)
        cy.get('.px-2').type('123456{enter}')
        cy.wait(3000)
        //settings
        cy.get('[href="/settings"]').click()
        cy.wait(3000)
        cy.get('ul > :nth-child(4) > .flex').click()
        cy.wait(3000)
        cy.get('.bg-slate-200 > :nth-child(6)').click()
        cy.wait(3000)
        cy.get('.p-2 > .css-10u1y7e-control').click()
        cy.wait(3000)
        cy.get('#react-select-5-option-2').click()
        cy.wait(5000)
        cy.get('.items-center > .w-32').click()
        cy.wait(3000)
        cy.get('.top-2 > :nth-child(2)').click()
        cy.wait(3000)
        //logout
        cy.get('[href="/logout"]').click()

        //Report Preferences: (254)
        cy.visit('https://alpha.xpropeller.com/signin')
     cy.wait(3000)
     cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
     cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
     cy.wait(3000)
     cy.get('.px-2').type('123456{enter}')
     cy.wait(3000)
      //settings
      cy.get('[href="/settings"]').click()
      cy.wait(3000)
      cy.get('ul > :nth-child(3) > .flex').click()
      cy.wait(3000)
      cy.get('.bg-slate-200 > :nth-child(6)').click()
      cy.wait(3000)
      cy.get('.p-2 > .css-10u1y7e-control').click()
      cy.wait(3000)
      cy.get('#react-select-5-option-2').click()
      cy.wait(5000)
      cy.get('.items-center > .w-32').click()
      cy.wait(3000)
      cy.get('.top-2 > :nth-child(2)').click()
      cy.wait(3000)
      //logout
      cy.get('[href="/logout"]').click()


      // User Activity Filtered By Facility: (356)
      cy.visit('https://alpha.xpropeller.com/signin')
      cy.wait(3000)
     cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
     cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
     cy.wait(3000)
     cy.get('.px-2').type('123456{enter}')
     cy.wait(3000)
     //settings
     cy.get('[href="/settings"]').click()
     cy.wait(5000)
     cy.get('ul > :nth-child(3) > .flex').click()
     cy.wait(3000)
     cy.get('.flex-row').click()
     cy.wait(3000)
     cy.get('#react-select-4-option-0').click()
     cy.wait(5000)
     cy.get('.flex-row > .items-center').click()
     cy.wait(3000)
     cy.get('.top-2 > :nth-child(2)').click()
     cy.wait(3000)
     //logout
     cy.get('[href="/logout"]').click()


          // User Activity Filtered By User (358)
          cy.visit('https://alpha.xpropeller.com/signin')
          cy.wait(3000)
          cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .px-2').type('wwsxpropellerr@gmail.com')
          cy.get('.relative > :nth-child(1) > .px-2').type('XPROwws@123{enter}')
          cy.wait(3000)
          cy.get('.px-2').type('123456{enter}')
          cy.wait(3000)
          //settings
          cy.get('[href="/settings"]').click()
          cy.wait(3000)
          cy.get('ul > :nth-child(3) > .flex').click()
          cy.wait(3000)
          cy.get('.bg-slate-200 > :nth-child(5)').click()
          cy.wait(3000)
          cy.get('.p-2 > .css-10u1y7e-control').click()
          cy.wait(3000)
          cy.get('#react-select-5-option-2').click()
          cy.wait(5000)
          cy.get('.flex-row > .items-center').click()
          cy.wait(3000)
          cy.get('.top-2 > :nth-child(1)').click()
          cy.wait(3000)
          //logout
          cy.get('[href="/logout"]').click()

         
         
    
    
       
   })
})